{
	"commands":
	[
	{
	"command":"info",
	"description":"get basic information about slave machine(s)"
	},
	{
	"command":"msgbox",
	"description":"msgbox <Title>;;<Message>"
	},
	{
	"command":"screenshot",
	"description":"retrieve live screenshot of slave machine(s)"
	},
	{
	"command":"getkeylog",
	"description":"return the keystrokes recorded since the last call to this command"
	},
	{
	"command":"blockinput",
	"description":"blocks user input from mouse and keyboard for upto a maximum of 1 minute"
	},
	{
	"command":"unblockinput",
	"description":"resumes user input from mouse and keyboard"
	}
	]
}